### ISSUE TITLE
fix odd issue

### ISSUE THREAD

**Issue by wiejakp** [wiejakp/python-sitemap-generator#5]
Fix error:

```a@b python-sitemap-generator % python3 python-sitemap-generator.py

http://local.test

Threads:  1  Queue:  0  Checked:  0  Link Threads:  0
Threads:  5  Queue:  4  Checked:  1  Link Threads:  0
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/aaa/sites/python-sitemap-generator/python-sitemap-generator.py", line 220, in run
    temp_data = fromstring(temp_content)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/soupparser.py", line 33, in fromstring
    return _parse(data, beautifulsoup, makeelement, **bsargs)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/soupparser.py", line 79, in _parse
    root = _convert_tree(tree, makeelement)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/soupparser.py", line 155, in _convert_tree
    converted = convert_node(e)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/soupparser.py", line 216, in convert_node
    return handler(bs_node, parent)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/soupparser.py", line 273, in convert_pi
    res = etree.ProcessingInstruction(*bs_node.split(' ', 1))
  File "src/lxml/etree.pyx", line 3078, in lxml.etree.ProcessingInstruction
ValueError: Invalid PI name 'b'xml''
Threads:  6  Queue:  4  Checked:  5  Link Threads:  2
Threads:  6  Queue:  2  Checked:  7  Link Threads:  3
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1470, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

**Comment by wiejakp** [comment]
https://github.com/wiejakp/python-sitemap-generator/pull/6
